---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

params:
  CONTEXT: repo
  DOCKERFILE: repo/ci/Dockerfile

inputs:
- name: repo
outputs:
- name: image
caches:
- path: cache

run:
  path: build
